<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Product>RTTCOMM</Product>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Views\Resourses\Pictures\AccountCircleAuthorized.png" />
    <None Remove="Views\Resourses\Pictures\AccountCircleNonAuthorized.png" />
    <None Remove="Views\Resourses\Pictures\Clear.png" />
    <None Remove="Views\Resourses\Pictures\ResetTv.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentModbus" Version="5.3.2" />
    <PackageReference Include="FontAwesome.Sharp" Version="6.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.77" />
    <PackageReference Include="OxyPlot.Wpf" Version="2.0.0" />
    <PackageReference Include="S7netplus" Version="0.20.0" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="2.1.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataAccess\DataAccess.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="application.db">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Views\Resourses\Pictures\AccountCircleAuthorized.png" />
    <Resource Include="Views\Resourses\Pictures\AccountCircleNonAuthorized.png" />
    <Resource Include="Views\Resourses\Pictures\Clear.png" />
    <Resource Include="Views\Resourses\Pictures\ResetTv.png" />
  </ItemGroup>

</Project>
